[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
size = 12

[cursor]
style = { shape="Block", blinking="Always" }
vi_mode_style = { shape="Underline", blinking="Always" }

[keyboard]
bindings = [
]

[window]
padding = { x = 12, y = 12 }

[general]
import = ["~/.config/alacritty/colors-alacritty.toml"]
