[colors.primary]
background = "#14131e"
foreground = "#d0d0d1"

[colors.cursor]
text = "#14131e"
cursor = "#d0d0d1"

[colors.vi_mode_cursor]
text = "#14131e"
cursor = "#d0d0d1"

[colors.search.matches]
foreground = "#14131e"
background = "#d0d0d1"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#9482cc"
background = "#9c9ca9"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#14131e"
red = "#ff9999"
green = "#ac76d0"
yellow = "#ff3a44"
blue = "#9a7ed0"
magenta = "#d971d9"
cyan = "#ef7437"
white = "#9c9ca9"

[colors.bright]
black = "#9482cc"
red = "#ffb2b2"
green = "#bf60f9"
yellow = "#ff4049"
blue = "#9f75f1"
magenta = "#f680f6"
cyan = "#ff925c"
white = "#d0d0d1"

[colors.dim]
black = "#d0d0d1"
red = "#ffb2b2"
green = "#f680f6"
yellow = "#ff4049"
blue = "#9f75f1"
magenta = "#bf60f9"
cyan = "#ff925c"
white = "#9482cc"

