foreground         #d0d0d1
background         #14131e
cursor             #d0d0d1

active_tab_foreground     #14131e
active_tab_background     #d0d0d1
inactive_tab_foreground   #d0d0d1
inactive_tab_background   #14131e

active_border_color   #d0d0d1
inactive_border_color #14131e
bell_border_color     #ff9999

color0       #14131e
color8       #9482cc
color1       #ff9999
color9       #ffb2b2
color2       #ac76d0
color10      #bf60f9
color3       #ff3a44
color11      #ff4049
color4       #9a7ed0
color12      #9f75f1
color5       #d971d9
color13      #f680f6
color6       #ef7437
color14      #ff925c
color7       #9c9ca9
color15      #d0d0d1
