require('packages.telescope')
require('packages.cwal')
require('packages.highlights')
require('packages.autopairs')
require('packages.tree-sitter')
require('packages.lsp')
require('packages.undotree')
require('packages.lualine')
require('packages.completion')
require('packages.indents')
require('packages.outline')

