background = 05040d
foreground = cdcdce
cursor-color = cdcdce
selection-background = cdcdce
selection-foreground = 05040d

palette = 0=#05040d
palette = 1=#ff94c7
palette = 2=#4756ff
palette = 3=#ffbfcd
palette = 4=#ffd38b
palette = 5=#a165f4
palette = 6=#be63b7
palette = 7=#9696a2
palette = 8=#7e7ec6
palette = 9=#ffaed5
palette = 10=#3c49ff
palette = 11=#ffced9
palette = 12=#ffdea8
palette = 13=#a059ff
palette = 14=#e06ad5
palette = 15=#cdcdce
